platform:ios, '8.0'
use_frameworks!

pod 'SwiftLint'

target 'GenAPI_Example' do
  pod 'GenAPI', :path => '../'

  target 'GenAPI_Tests' do
    inherit! :search_paths
    pod 'GenAPI', :path => '../'
    
  end
end
